Bot frame created
Markelych32/Link_Tracker pull request #1
Opened 2024-02-15 16:23 UTC by Markelych32

Written tests for commands
Added command button

2024-02-18 16:09 UTC, SHvatov requested changes
@Markelych32 привет! Меня зовут Сергей, и в этом семестре я буду проверять твои работы :) Если будут какие-то вопросы, можешь их смело задавать мне. Еще я создал небольшую группу в телеге для всяких анонсов, чисто для тех, кто в моей группе - https://t.me/+KoDhaQZiHokwNDcy.

Оставил пару комментариев, посмотри их, пожалуйста.

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/StartCommand.java
> +        return repository.findByChatId(chatId).isPresent()
```java 
return repository.findByChatId(chatId)
            .filter(it -> UserState.REGISTRATION == it.getState())
            .isPresent();
```

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/StartCommand.java
> +        return repository.findByChatId(chatId).isPresent()
И стоит избегать повторных запросов в репозиториях. Хорошо, если есть кэш. А вот если его нет, то перфоманс может сильно просесть.

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/StartCommand.java
> +        User user = repository.findByChatId(chatId).get();
Зачем тут повторный поиск?

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/TrackCommand.java
> +        if (user.getState() == UserState.TRACK) {
Достаточно сложная стейт-машина получается. Ты точно хочешь пойти по такому пути, а не просто `/команда <аругменты>`?

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/command/TrackCommand.java
> +        if (user.getState() == UserState.TRACK) {
Если да, то cтоит декомпозировать метод - сейчас он большой и не очень понятный.

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/repository/TempRepository.java
> +public class TempRepository {
Нарушается Interface Segregation принцип, класс обещает перерасти в god object, а названия методов становятся неговорящими. Давай уже сейчас разделим его по сущностям.

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/utils/Bot.java
> +public interface Bot extends AutoCloseable, UpdatesListener {
Точно нужен интерфейс?

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/utils/MessageProcessor.java
> +    private final HelpCommand helpCommand;
Можно команды сделать компонентами и заинжектить их. Будет гораздо проще + добавление новой команды не требует дополнительных телодвижений.

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/utils/MessageProcessor.java
> +public class MessageProcessor implements UserMessageProcessor {
Название интерфейса более конкретное, чем у реализации. Давай их просто объединим.

2024-02-18 16:09 UTC, SHvatov commented on bot/src/main/java/edu/java/bot/utils/MessageProcessor.java
> +        List<? extends Command> rightCommand = commands()
```java
    @Override
    public SendMessage process(Update update) {
        return commands().stream()
            .filter(command -> command.supports(update))
            .findFirst()
            .map(it -> it.handle(update))
            .orElseGet(() -> new SendMessage(update.message().chat().id(), TEXT).parseMode(ParseMode.Markdown));
    }
```

2024-02-18 16:09 UTC, SHvatov commented on bot/src/test/java/edu/bot/command/HelpCommandTest.java
> +    @Test
Не хватает информации о coverage в инфе об МРе.

2024-02-20 14:05 UTC, Markelych32 commented
> ### Code Coverage
> Overall Project	NaN% **`NaN%`**	🍏
> > There is no coverage information present for the Files changed

2024-02-20 14:05 UTC, closed without merging